---
- name: install mysql python dependecies
  hosts: all

  tasks:
          - name: install packages
            pip:
                    name:
                            - PyMySQL
                    state: latest

          - name: install collection
            shell: ansible-galaxy collection install community.mysql
