- name: install web packages
  apt:
    name: "{{ web_packages }}"
    state: latest

- name: install db packages
  apt:
    name: "{{ db_packages }}"
    state: latest

- name: install other packages
  apt:
    name: "{{ extra_packages }}"
    state: latest
