- name: install web packages
  package:
    name: "{{ web_packages }}"
    state: present

- name: install db packages
  package:
    name: "{{ db_packages }}"
    state: present

- name: install other packages
  package:
    name: "{{ extra_packages }}"
    state: present
